vector_db:
  collection_name: "rag_collection"
  embedding_model: "BAAI/bge-m3"
  uri: "./data/vector_db/milvus_demo.db"
  index_params:
    index_type: "FLAT"
    metric_type: "L2"

llm:
  model: "mistral-nemo"
  temperature: 0.7
  max_tokens: 500

processing:
  chunk_size: 1000
  chunk_overlap: 200
